name: XcodeGenSample
options:
  carthageBuildPath: "./Carthage/Build"
settings:
  DEVELOPMENT_TEAM: 9E87K75Q44
targets:
  XcodeGenSample:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    attributes:
      ProvisioningStyle: Automatic
    sources:
      - XcodeGenSample
      - Vendor
    configFiles:
      Debug: configs/Debug.xcconfig
      Release: configs/Release.xcconfig
    settings:
      base:
        INFOPLIST_FILE: XcodeGenSample/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nghianv.xcodegen
        CODE_SIGN_ENTITLEMENTS: XcodeGenSample/XcodeGenSample.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
        SWIFT_OBJC_BRIDGING_HEADER: Bridge/Bridging-Header.h
      configs:
        Debug:
          DEBUG_MODE: YES
        Release:
          DEBUG_MODE: NO
    dependencies:
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift
      - target: DynamicFramework
      - target: StaticFramework
      # - target: Database
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES

  DynamicFramework:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: DynamicFramework
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nghianv.xcodegen.DynamicFramework
      INFOPLIST_FILE: DynamicFramework/Info.plist
    dependencies:
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift

  StaticFramework:
    type: framework.static
    platform: iOS
    deploymentTarget: "10.0"
    sources: StaticFramework
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nghianv.xcodegen.StaticFramework
      INFOPLIST_FILE: StaticFramework/Info.plist
    dependencies:
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift

  # Config:
  #   type: framework
  #   platform: iOS
  #   deploymentTarget: "10.0"
  #   sources: LocalFramework/Config
  #   settings:
  #     PRODUCT_BUNDLE_IDENTIFIER: com.nghianv.xcodegen.Config
  #     INFOPLIST_FILE: LocalFramework/Config/Info.plist

