name: XcodeGenSample
options:
  preGenCommand: echo Before
  postGenCommand: echo After
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top
  
packages:
  SwiftyUtils:
    url: https://github.com/tbaranes/SwiftyUtils
    from: 5.0.0

  SwiftyBeaver:
    url: https://github.com/SwiftyBeaver/SwiftyBeaver
    from: 1.0.0
    
settings:
  DEVELOPMENT_TEAM: 9E87K75Q44

schemes:
  XcodeGenSample:
    build:
      targets:
        XcodeGenSample: all
      parallelizeBuild: true
      buildImplicitDependencies: true
  
targets:
  XcodeGenSample:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    attributes:
      ProvisioningStyle: Automatic

    sources:
      - XcodeGenSample
      - Vendor
      - path: App/Sources
        name: Sources
      - path: Resources

    configFiles:
      Debug: configs/Debug.xcconfig
      Release: configs/Release.xcconfig

    settings:
      base:
        INFOPLIST_FILE: XcodeGenSample/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nghianv.xcodegen
        CODE_SIGN_ENTITLEMENTS: XcodeGenSample/XcodeGenSample.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
        SWIFT_OBJC_BRIDGING_HEADER: Bridge/Bridging-Header.h
      configs:
        Debug:
          DEBUG_MODE: YES
        Release:
          DEBUG_MODE: NO
    dependencies:
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift
      - target: DynamicFramework
      - target: StaticFramework
      - package: SwiftyUtils
      - package: SwiftyBeaver
      # - target: Database
    scheme:
      environmentVariables:
        ENABLE_SIGNPOST: YES

  DynamicFramework:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: 
      - Libs/DynamicFramework/Sources
      - path: Libs/DynamicFramework/Supporting Files/DynamicFramework.h
        buildPhase: headers
        headerVisibility: public
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nghianv.xcodegen.DynamicFramework
      INFOPLIST_FILE: Libs/DynamicFramework/Info.plist
    dependencies:
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift

  StaticFramework:
    type: framework
    platform: iOS
    scheme:
      gatherCoverageData: true
    sources:
      - Libs/StaticFramework/Sources
      - path: Libs/StaticFramework/Supporting Files/StaticFramework.h
        buildPhase: headers
        headerVisibility: public

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nghianv.xcodegen.StaticFramework
      INFOPLIST_FILE: Libs/StaticFramework/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 10.0
    dependencies:
      - sdk: Contacts.framework
      - sdk: libc++.tbd
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxSwift

